// Package aimiddleware provides ABI bindings that are automatically generated by abigen for interacting with
// the AiMiddleware contract. The aimiddleware directory also contains helper modules for convenience.
package aimiddleware
